### ISSUE TITLE
Conform 2.2.2 and Distillery Runtime Error

### ISSUE THREAD

**Issue by geofflane** [bitwalker/conform#113]
Running with Conform 2.1.2 and the latest Distillery the build works and starts fine. When I update to Conform 2.2.2 (with no other changes) and I want to run the built application then I get the following `invalid mfa` error.

```
2017-03-01 10:37:17.763 [info] Application mega_maid exited: MegaMaid.start(:normal, []) returned an error: shutdown: failed to start child: MegaMaid.Endpoint
    ** (EXIT) bad start spec: invalid mfa: {{:__aliases__, [line: 197], [:Phoenix, :PubSub, :PG2]}, :start_link, [MegaMaid.PubSub, [fastlane: Phoenix.Channel.Server, pool_size: 1, adapter: {:__aliases__, [line: 197], [:Phoenix, :PubSub, :PG2]}, name: {:__aliases__, [line: 189], [:MegaMaid, :PubSub]}]]}
{"Kernel pid terminated",application_controller,"{application_start_failure,mega_maid,{{shutdown,{failed_to_start_child,'Elixir.MegaMaid.Endpoint',{start_spec,{invalid_mfa,{{'__aliases__',[{line,197}],['Phoenix','PubSub','PG2']},start_link,['Elixir.MegaMaid.PubSub',[{fastlane,'Elixir.Phoenix.Channel.Server'},{pool_size,1},{adapter,{'__aliases__',[{line,197}],['Phoenix','PubSub','PG2']}},{name,{'__aliases__',[{line,189}],['MegaMaid','PubSub']}}]]}}}}},{'Elixir.MegaMaid',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,mega_maid,{{shutdown,{failed_to_start_child,'Elixir.MegaMaid.Endpoint',{start_spec,{invalid_mfa,{{'__aliases__',[{line,197}],

Crash dump is being written to: erl_crash.dump...done
```

This is a Phoenix 1.2.1, Elixir 1.4 application.

**Comment by bitwalker** [comment]
MegaMaid, awesome :)

Could you show me your `.conf` and `.schema.exs` from the release? Feel free to strip any sensitive information, but I'll need that to reproduce the issue.

**Comment by geofflane** [comment]
@bitwalker Here you go.

(I renamed a couple of things, so hopefully didn't muck anything up.) Thanks for the help.

mega_maid.conf
```
# The name of the issuer of the security token. Really just this application's name.
guardian.Elixir.Guardian.issuer = "MegaMaid"

# Should the issuer of the token be verified? The answer is yes.
guardian.Elixir.Guardian.verify_issuer = true

# The secret key used to encrypt the Guardian token. This should be kept secure to ensure fake tokens cannot be generated.
guardian.Elixir.Guardian.secret_key = "not secret, override in mega_maid.conf"

# The format of the logs.
logger.console.format = "$date $time $metadata[$level] $message
"

# Metadata to add to the logs. DO NOT CHANGE THIS IF YOU DO NOT KNOW WHAT THAT MEANS.
logger.console.metadata = request_id

# The Logging level. One of info, error, warn, debug
# Allowed values: info, error, warn, debug
logger.level = info

# The port that the webserver listens on locally.
mega_maid.Elixir.MegaMaid.Endpoint.http.port = 4000

# The external host name of the site. Needs to be correct so that email URLs are correct, for example.
mega_maid.Elixir.MegaMaid.Endpoint.url.host = "localhost"

# The external protocol of the site. Needs to be correct so that email URLs are correct, for example
mega_maid.Elixir.MegaMaid.Endpoint.url.scheme = "https"

# The external port of the site. Needs to be correct so that email URLs are correct, for example.
mega_maid.Elixir.MegaMaid.Endpoint.url.port = 443

# The URLs that this site can be accessed with. This allows CORS checks to work correctly.
mega_maid.Elixir.MegaMaid.Endpoint.check_origin = "//localhost"

# Secret key used for encrypting cookies.
mega_maid.Elixir.MegaMaid.Endpoint.secret_key_base = "changeme"

# The database adapter. DO NOT CHANGE THIS.
mega_maid.Elixir.MegaMaid.Repo.adapter = Elixir.Ecto.Adapters.Postgres

# The database username used to conect to the DAT database.
mega_maid.Elixir.MegaMaid.Repo.username = "postgres"

# The database password used to conect to the DAT database.
mega_maid.Elixir.MegaMaid.Repo.password = "secret"

# The database host where the DAT database is running
mega_maid.Elixir.MegaMaid.Repo.hostname = "localhost"

# The database name of the DAT database.
mega_maid.Elixir.MegaMaid.Repo.database = "dat_db"

# The DB conection pool size
mega_maid.Elixir.MegaMaid.Repo.pool_size = 20

# The Mailgun domain.
mega_maid.mailgun_domain = "https://api.mailgun.net/v3/sandboxxxxx.mailgun.org"

# The Mailgun API key
mega_maid.mailgun_key = "key-xxxx"

# The URL of the Pulsar API to push data to.
mega_maid.example_live_endpoint = "http://pulsar.example.com/api"

mega_maid.mode = normal

```

mega_maid.schema.exs
```
@moduledoc """
A schema is a keyword list which represents how to map, transform, and validate
configuration values parsed from the .conf file. The following is an explanation of
each key in the schema definition in order of appearance, and how to use them.

## Import

A list of application names (as atoms), which represent apps to load modules from
which you can then reference in your schema definition. This is how you import your
own custom Validator/Transform modules, or general utility modules for use in
validator/transform functions in the schema. For example, if you have an application
`:foo` which contains a custom Transform module, you would add it to your schema like so:

`[ import: [:foo], ..., transforms: ["myapp.some.setting": MyApp.SomeTransform]]`

## Extends

A list of application names (as atoms), which contain schemas that you want to extend
with this schema. By extending a schema, you effectively re-use definitions in the
extended schema. You may also override definitions from the extended schema by redefining them
in the extending schema. You use `:extends` like so:

`[ extends: [:foo], ... ]`

## Mappings

Mappings define how to interpret settings in the .conf when they are translated to
runtime configuration. They also define how the .conf will be generated, things like
documention, @see references, example values, etc.

See the moduledoc for `Conform.Schema.Mapping` for more details.

## Transforms

Transforms are custom functions which are executed to build the value which will be
stored at the path defined by the key. Transforms have access to the current config
state via the `Conform.Conf` module, and can use that to build complex configuration
from a combination of other config values.

See the moduledoc for `Conform.Schema.Transform` for more details and examples.

## Validators

Validators are simple functions which take two arguments, the value to be validated,
and arguments provided to the validator (used only by custom validators). A validator
checks the value, and returns `:ok` if it is valid, `{:warn, message}` if it is valid,
but should be brought to the users attention, or `{:error, message}` if it is invalid.

See the moduledoc for `Conform.Schema.Validator` for more details and examples.
"""
[
  extends: [],
  import: [],
  mappings: [
    "phoenix.generators.migration": [
      commented: true,
      datatype: :atom,
      default: true,
      doc: "Provide documentation for phoenix.generators.migration here.",
      hidden: false,
      to: "phoenix.generators.migration"
    ],
    "phoenix.generators.binary_id": [
      commented: true,
      datatype: :atom,
      default: false,
      doc: "Provide documentation for phoenix.generators.binary_id here.",
      hidden: false,
      to: "phoenix.generators.binary_id"
    ],
    "guardian.Elixir.Guardian.issuer": [
      commented: true,
      datatype: :binary,
      default: "MegaMaid",
      doc: "The name of the issuer of the security token. Really just this application's name.",
      hidden: false,
      to: "guardian.Elixir.Guardian.issuer"
    ],
    # This one is broken in Conform
    # "guardian.Elixir.Guardian.ttl": [
    #   commented: false,
    #   datatype: {:atom, :atom},
    #   default: {30, :days},
    #   doc: "Provide documentation for guardian.Elixir.Guardian.ttl here.",
    #   hidden: false,
    #   to: "guardian.Elixir.Guardian.ttl"
    # ],
    "guardian.Elixir.Guardian.verify_issuer": [
      commented: true,
      datatype: :atom,
      default: true,
      doc: "Should the issuer of the token be verified? The answer is yes.",
      hidden: false,
      to: "guardian.Elixir.Guardian.verify_issuer"
    ],
    "guardian.Elixir.Guardian.secret_key": [
      commented: true,
      datatype: :binary,
      default: "not secret, override in mega_maid.conf",
      doc: "The secret key used to encrypt the Guardian token. This should be kept secure to ensure fake tokens cannot be generated.",
      hidden: false,
      to: "guardian.Elixir.Guardian.secret_key"
    ],
    "guardian.Elixir.Guardian.serializer": [
      commented: false,
      datatype: :atom,
      default: MegaMaid.GuardianSerializer,
      doc: "The module that converts from the Guardian token to a User and back. DO NOT CHANGE THIS.",
      hidden: true,
      to: "guardian.Elixir.Guardian.serializer"
    ],
    "guardian.Elixir.Guardian.permissions": [
      commented: false,
      datatype: :binary,
      doc: "Provide documentation for guardian.Elixir.Guardian.permissions here.",
      hidden: false,
      to: "guardian.Elixir.Guardian.permissions"
    ],
    "logger.console.format": [
      commented: true,
      datatype: :binary,
      default: """
      $date $time $metadata[$level] $message
      """,
      doc: "The format of the logs.",
      hidden: false,
      to: "logger.console.format"
    ],
    "logger.console.metadata": [
      commented: true,
      datatype: [
        list: :atom
      ],
      default: [
        :request_id
      ],
      doc: "Metadata to add to the logs. DO NOT CHANGE THIS IF YOU DO NOT KNOW WHAT THAT MEANS.",
      hidden: false,
      to: "logger.console.metadata"
    ],
    "logger.level": [
      commented: true,
      datatype: [enum: [:info, :error, :warn, :debug]],
      default: :info,
      doc: "The Logging level.",
      hidden: false,
      to: "logger.level"
    ],
    "mega_maid.Elixir.MegaMaid.Endpoint.render_errors.accepts": [
      commented: false,
      datatype: [
        list: :binary
      ],
      default: [
        "html",
        "json"
      ],
      doc: "Provide documentation for mega_maid.Elixir.MegaMaid.Endpoint.render_errors.accepts here.",
      hidden: true,
      to: "mega_maid.Elixir.MegaMaid.Endpoint.render_errors.accepts"
    ],
    "mega_maid.Elixir.MegaMaid.Endpoint.pubsub.name": [
      commented: true,
      datatype: :atom,
      default: MegaMaid.PubSub,
      doc: "DO NOT CHANGE THIS",
      hidden: true,
      to: "mega_maid.Elixir.MegaMaid.Endpoint.pubsub.name"
    ],
    "mega_maid.Elixir.MegaMaid.Endpoint.pubsub.adapter": [
      commented: false,
      datatype: :atom,
      default: Phoenix.PubSub.PG2,
      doc: "Module for pubsup adapter. DO NOT CHANGE THIS.",
      hidden: true,
      to: "mega_maid.Elixir.MegaMaid.Endpoint.pubsub.adapter"
    ],
    "mega_maid.Elixir.MegaMaid.Endpoint.http.port": [
      commented: true,
      datatype: :integer,
      default: 4000,
      doc: "The port that the webserver listens on locally.",
      hidden: false,
      to: "mega_maid.Elixir.MegaMaid.Endpoint.http.port"
    ],
    "mega_maid.Elixir.MegaMaid.Endpoint.url.host": [
      commented: true,
      datatype: :binary,
      default: "dat.example.com",
      doc: "The external host name of the site. Needs to be correct so that email URLs are correct, for example.",
      hidden: false,
      to: "mega_maid.Elixir.MegaMaid.Endpoint.url.host"
    ],
    "mega_maid.Elixir.MegaMaid.Endpoint.url.scheme": [
      commented: true,
      datatype: :binary,
      default: "https",
      doc: "The external protocol of the site. Needs to be correct so that email URLs are correct, for example",
      hidden: false,
      to: "mega_maid.Elixir.MegaMaid.Endpoint.url.scheme"
    ],
    "mega_maid.Elixir.MegaMaid.Endpoint.url.port": [
      commented: true,
      datatype: :integer,
      default: 443,
      doc: "The external port of the site. Needs to be correct so that email URLs are correct, for example.",
      hidden: false,
      to: "mega_maid.Elixir.MegaMaid.Endpoint.url.port"
    ],
    "mega_maid.Elixir.MegaMaid.Endpoint.root": [
      commented: false,
      datatype: :binary,
      default: ".",
      doc: "Provide documentation for mega_maid.Elixir.MegaMaid.Endpoint.root here.",
      hidden: true,
      to: "mega_maid.Elixir.MegaMaid.Endpoint.root"
    ],
    # "mega_maid.Elixir.MegaMaid.Endpoint.force_ssl.rewrite_on": [
    #   commented: false,
    #   datatype: [
    #     list: :atom
    #   ],
    #   default: [
    #     :x_forwarded_proto
    #   ],
    #   doc: "Provide documentation for mega_maid.Elixir.MegaMaid.Endpoint.force_ssl.rewrite_on here.",
    #   hidden: false,
    #   to: "mega_maid.Elixir.MegaMaid.Endpoint.force_ssl.rewrite_on"
    # ],
    "mega_maid.Elixir.MegaMaid.Endpoint.check_origin": [
      commented: false,
      datatype: [
        list: :binary
      ],
      default: [
        "//dat.example.com}"
      ],
      doc: "The URLs that this site can be accessed with. This allows CORS checks to work correctly.",
      hidden: false,
      to: "mega_maid.Elixir.MegaMaid.Endpoint.check_origin"
    ],
    "mega_maid.Elixir.MegaMaid.Endpoint.cache_static_manifest": [
      commented: false,
      datatype: :binary,
      default: "priv/static/manifest.json",
      doc: "The manifest containing the mapping of file names to their fingerprinted files.",
      hidden: true,
      to: "mega_maid.Elixir.MegaMaid.Endpoint.cache_static_manifest"
    ],
    "mega_maid.Elixir.MegaMaid.Endpoint.secret_key_base": [
      commented: true,
      datatype: :binary,
      default: "changeme",
      doc: "Secret key used for encrypting cookies.",
      hidden: false,
      to: "mega_maid.Elixir.MegaMaid.Endpoint.secret_key_base"
    ],
    "mega_maid.Elixir.MegaMaid.Endpoint.server": [
      commented: false,
      datatype: :atom,
      default: true,
      doc: "DO NOT CHANGE THIS.",
      hidden: true,
      to: "mega_maid.Elixir.MegaMaid.Endpoint.server"
    ],
    "mega_maid.Elixir.MegaMaid.Repo.adapter": [
      commented: false,
      datatype: :atom,
      default: Ecto.Adapters.Postgres,
      doc: "The database adapter. DO NOT CHANGE THIS.",
      hidden: false,
      to: "mega_maid.Elixir.MegaMaid.Repo.adapter"
    ],
    "mega_maid.Elixir.MegaMaid.Repo.username": [
      commented: true,
      datatype: :binary,
      default: "dat_user",
      doc: "The database username used to conect to the DAT database.",
      hidden: false,
      to: "mega_maid.Elixir.MegaMaid.Repo.username"
    ],
    "mega_maid.Elixir.MegaMaid.Repo.password": [
      commented: false,
      datatype: :binary,
      default: "SECRET",
      doc: "The database password used to conect to the DAT database.",
      hidden: false,
      to: "mega_maid.Elixir.MegaMaid.Repo.password"
    ],
    "mega_maid.Elixir.MegaMaid.Repo.hostname": [
      commented: true,
      datatype: :binary,
      default: "DB_HOST",
      doc: "The database host where the DAT database is running",
      hidden: false,
      to: "mega_maid.Elixir.MegaMaid.Repo.hostname"
    ],
    "mega_maid.Elixir.MegaMaid.Repo.database": [
      commented: true,
      datatype: :binary,
      default: "dat_db",
      doc: "The database name of the DAT database.",
      hidden: false,
      to: "mega_maid.Elixir.MegaMaid.Repo.database"
    ],
    "mega_maid.Elixir.MegaMaid.Repo.pool_size": [
      commented: true,
      datatype: :integer,
      default: 20,
      doc: "The DB conection pool size",
      hidden: false,
      to: "mega_maid.Elixir.MegaMaid.Repo.pool_size"
    ],
    "mega_maid.example_live_puller": [
      commented: false,
      datatype: :atom,
      default: ExampleLive.Sync.Puller,
      doc: "Provide documentation for mega_maid.example_live_puller here.",
      hidden: true,
      to: "mega_maid.example_live_puller"
    ],
    "mega_maid.example_live_deleter": [
      commented: false,
      datatype: :atom,
      default: ExampleLive.Sync.Deleter,
      doc: "Provide documentation for mega_maid.example_live_deleter here.",
      hidden: true,
      to: "mega_maid.example_live_deleter"
    ],
    "mega_maid.mode": [
      commented: true,
      datatype: [enum: [:college, :pro]],
      default: :pro,
      doc: "Which mode to run in, college or pro",
      hidden: false,
      to: "mega_maid.mode"
    ],
    "mega_maid.mailgun_domain": [
      commented: false,
      datatype: :binary,
      default: "https://api.mailgun.net/v3/sandboxxxx.mailgun.org",
      doc: "The Mailgun domain.",
      hidden: false,
      to: "mega_maid.mailgun_domain"
    ],
    "mega_maid.mailgun_key": [
      commented: false,
      datatype: :binary,
      default: "key-xxxxx",
      doc: "The Mailgun API key",
      hidden: false,
      to: "mega_maid.mailgun_key"
    ],
    "mega_maid.example_live_endpoint": [
      commented: false,
      datatype: :binary,
      default: "http://pulsar.example.com/api",
      doc: "The URL of the Pulsar API to push data to.",
      hidden: false,
      to: "mega_maid.example_live_endpoint"
    ],
    "mega_maid.example_live_pusher": [
      commented: false,
      datatype: :atom,
      default: ExampleLive.Sync.Pusher,
      doc: "Provide documentation for mega_maid.example_live_pusher here.",
      hidden: true,
      to: "mega_maid.example_live_pusher"
    ]
  ],
  transforms: [],
  validators: []
]
```

**Comment by bitwalker** [comment]
Do you have a copy of the generated `sys.config` from the release when this error occurred? It should be under `<deploy_dir>/var/sys.config`. If you don't have it, mind trying to boot your release again and grabbing that file?

Looking at your conf and schema, I'm not sure where the bad config is coming from - which implies either conform is munging something present in the default `sys.config` (i.e. the one generated from `config.exs`), or there is something dynamic happening in `config.exs` which can't be translated to `sys.config`, and will need to be handled differently. Seeing the generated `sys.config` should narrow things down considerably.

**Comment by suaron** [comment]
@bitwalker  I faced with similar issue

```
→ mix conform.configure


You already have a .conf at config/ipo_backend.dev.conf.
Do you want to overwrite this config file with a new one?
 [Yn]

** (ArgumentError) argument error
    :erlang.atom_to_binary({:__aliases__, [line: 106], [:IpoBackend, :Repo]}, :utf8)
    lib/conform/translate.ex:434: Conform.Translate.write_datatype/3
    (elixir) lib/enum.ex:1229: Enum."-map/2-lists^map/1-0-"/2
    lib/conform/translate.ex:463: Conform.Translate.write_datatype/3
    lib/conform/translate.ex:61: anonymous fn/2 in Conform.Translate.to_conf/1
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/mix/tasks/conform.configure.ex:43: Mix.Tasks.Conform.Configure.do_run/1
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
```

**Comment by geofflane** [comment]
@bitwalker This is the generated sys.config. You can see the tuples that the error is complaining about that are wrong in there. Those get inserted only after I run the application and conform does its work.

```
%%Generated - edit /Users/geoff/projects/mega-maid/rel/mega_maid/mega_maid.conf or /Users/geoff/projects/mega-maid/rel/mega_maid/mega_maid.conf/sys.config
[{ex_statsd,[{host,<<"dockerhost">>},{namespace,<<"app">>},{port,8125}]},
 {guardian,
     [{'Elixir.Guardian',
          [{issuer,<<"MegaMaid">>},
           {permissions,#{default => [tbd]}},
           {secret_key,<<"not secret, override in mega_maid.conf">>},
           {serializer,
               {'__aliases__',[{line,107}],['MegaMaid','GuardianSerializer']}},
           {ttl,{30,days}},
           {verify_issuer,true}]}]},
 {logger,
     [{console,
          [{format,<<"$date $time $metadata[$level] $message\n">>},
           {metadata,[request_id,user_id]}]},
      {level,info}]},
 {mega_maid,
     [{'Elixir.MegaMaid.Endpoint',
          [{cache_static_manifest,<<"priv/static/manifest.json">>},
           {check_origin,[<<"//">>,<<"//localhost">>]},
           {http,[{compress,true},{port,4000}]},
           {pubsub,
               [{adapter,
                    {'__aliases__',[{line,173}],['Phoenix','PubSub','PG2']}},
                {name,{'__aliases__',[{line,165}],['MegaMaid','PubSub']}}]},
           {render_errors,[{accepts,[<<"html">>,<<"json">>]}]},
           {root,<<".">>},
           {secret_key_base,<<"changeme">>},
           {server,true},
           {url,[{host,<<"localhost">>},{port,443},{scheme,<<"https">>}]},
           {version,<<"1.5.12">>}]},
      {'Elixir.MegaMaid.Repo',
          [{adapter,'Elixir.Ecto.Adapters.Postgres'},
           {database,<<"dat_db">>},
           {hostname,<<"localhost">>},
           {loggers,
               [{'Elixir.Ecto.LogEntry',log,[]},
                {'Elixir.Metrex.EctoLogger',log,[]}]},
           {password,<<"secret">>},
           {pool_size,20},
           {username,<<"postgres">>}]},
      {ecto_repos,['Elixir.MegaMaid.Repo']},
      {mailgun_domain,
          <<"https://api.mailgun.net/v3/sandboxxxxx.mailgun.org">>},
      {mailgun_key,<<"key-xxxx">>},
      {mode,pro},
      {namespace,'Elixir.MegaMaid'},
      {example_live_deleter,
          {'__aliases__',[{line,325}],['ExampleLive','Sync','Deleter']}},
      {example_live_endpoint,<<"http://pulsar.example.com/api">>},
      {example_live_puller,
          {'__aliases__',[{line,317}],['ExampleLive','Sync','Puller']}},
      {example_live_pusher,
          {'__aliases__',[{line,365}],['ExampleLive','Sync','Pusher']}},
      {sync_logger,'Elixir.ExampleLive.Sync.SyncLogServer'}]},
 {phoenix,[{generators,[{binary_id,false},{migration,true}]}]},
 {sasl,[{errlog_type,error}]}].

```

The Endpoint config, for example, should look like this:
```
      {'Elixir.MegaMaid.Endpoint',
          [{render_errors,[{accepts,[<<"html">>,<<"json">>]}]},
           {pubsub,
               [{name,'Elixir.MegaMaid.PubSub'},
                {adapter,'Elixir.Phoenix.PubSub.PG2'}]},
           {http,[{compress,true},{port,{system,<<"PORT">>}}]},
           {url,[{host,nil},{scheme,<<"https">>},{port,443}]},
           {root,<<".">>},
           {check_origin,[<<"//">>]},
           {cache_static_manifest,<<"priv/static/manifest.json">>},
           {secret_key_base,nil},
           {server,true},
           {version,<<"1.5.12">>}]},
```

**Comment by bitwalker** [comment]
Could you give master a shot? I've pushed a variety of fixes and added your example as a test

**Comment by geofflane** [comment]
@bitwalker The generated file looks like it no longer shows the problem, but the error seems to be the same. I cleaned out the build directory completely, ran a new build with the the github version of conform.

Only other thing I can think is I'm on the latest Erlang 19.2.3:
Erlang/OTP 19 [erts-8.2.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace] Elixir 1.4.2

```
2017-03-03 14:22:46.972 [info] Application mega_maid exited: MegaMaid.start(:normal, []) returned an error: shutdown: failed to start child: MegaMaid.Endpoint
    ** (EXIT) bad start spec: invalid mfa: {{:__aliases__, [line: 197], [:Phoenix, :PubSub, :PG2]}, :start_link, [MegaMaid.PubSub, [fastlane: Phoenix.Channel.Server, pool_size: 1, adapter: {:__aliases__, [line: 197], [:Phoenix, :PubSub, :PG2]}, name: {:__aliases__, [line: 189], [:MegaMaid, :PubSub]}]]}
{"Kernel pid terminated",application_controller,"{application_start_failure,mega_maid,{{shutdown,{failed_to_start_child,'Elixir.MegaMaid.Endpoint',{start_spec,{invalid_mfa,{{'__aliases__',[{line,197}],['Phoenix','PubSub','PG2']},start_link,['Elixir.MegaMaid.PubSub',[{fastlane,'Elixir.Phoenix.Channel.Server'},{pool_size,1},{adapter,{'__aliases__',[{line,197}],['Phoenix','PubSub','PG2']}},{name,{'__aliases__',[{line,189}],['MegaMaid','PubSub']}}]]}}}}},{'Elixir.MegaMaid',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,mega_maid,{{shutdown,{failed_to_start_child,'Elixir.MegaMaid.Endpoint',{start_spec,{invalid_mfa,{{'__aliases__',[{line,197}],

Crash dump is being written to: erl_crash.dump...done
```

The generated output in var/sys.config looks fine:
```
      {'Elixir.MegaMaid.Endpoint',
          [{render_errors,[{accepts,[<<"html">>,<<"json">>]}]},
           {pubsub,
               [{name,'Elixir.MegaMaid.PubSub'},
                {adapter,'Elixir.Phoenix.PubSub.PG2'}]},
           {http,[{compress,true},{port,{system,<<"PORT">>}}]},
           {url,[{host,nil},{scheme,<<"https">>},{port,443}]},
           {root,<<".">>},
           {check_origin,[<<"//">>]},
           {cache_static_manifest,<<"priv/static/manifest.json">>},
           {secret_key_base,nil},
           {server,true},
           {root,<<".">>},
           {version,<<"1.6.5">>}]},
```

**Comment by bitwalker** [comment]
I'm unable to reproduce with Elixir 1.4/Erlang 19.2. I have a test in `test/config_test.exs` for this issue, which uses your config, schema, and .conf. Could you give me the steps you are using to reproduce?

**Comment by milafrerichs** [comment]
had the same issue as @suaron and using the master fixed it for me.

**Comment by bitwalker** [comment]
Awesome, thanks for following up!
