### ISSUE TITLE
no function clause matching in Conform.Translate.to_config

### ISSUE THREAD

**Issue by kenuyx** [bitwalker/conform#124]
When I was using `edeliver` to start a well-deployed app in a staging host, I got an error like this.

```
$ mix edeliver start

EDELIVER ARMREST WITH START COMMAND

-----> starting staging servers

staging node:

  user    : diqi
  host    : diqi-staging
  path    : /home/diqi
  response: ** (FunctionClauseError) no function clause matching in Conform.Translate.to_config/3
    (conform) lib/conform/translate.ex:83: Conform.Translate.to_config(%Conform.Schema{extends: [], import: [], mappings: [%Conform.Schema.Mapping{commented: false, datatype: :atom, default: Ecto.Adapters.Postgres, doc: "Provide documentation for armrest.Elixir.Armrest.Repo.adapter here.", env_var: nil, hidden: false, include_default: nil, name: "armrest.Elixir.Armrest.Repo.adapter", persist: true, see: "", to: "armrest.Elixir.Armrest.Repo.adapter", validators: []}, %Conform.Schema.Mapping{commented: false, datatype: :binary, default: "postgres", doc: "Provide documentation for armrest.Elixir.Armrest.Repo.database here.", env_var: nil, hidden: false, include_default: nil, name: "armrest.Elixir.Armrest.Repo.database", persist: true, see: "", to: "armrest.Elixir.Armrest.Repo.database", validators: []}, %Conform.Schema.Mapping{commented: false, datatype: :binary, default: "postgres", doc: "Provide documentation for armrest.Elixir.Armrest.Repo.username here.", env_var: nil, hidden: false, include_default: nil, name: "armrest.Elixir.Armrest.Repo.username", persist: true, see: "", to: "armrest.Elixir.Armrest.Repo.username", validators: []}, %Conform.Schema.Mapping{commented: false, datatype: :binary, default: nil, doc: "Provide documentation for armrest.Elixir.Armrest.Repo.password here.", env_var: nil, hidden: false, include_default: nil, name: "armrest.Elixir.Armrest.Repo.password", persist: true, see: "", to: "armrest.Elixir.Armrest.Repo.password", validators: []}, %Conform.Schema.Mapping{commented: false, datatype: :binary, default: "localhost", doc: "Provide documentation for armrest.Elixir.Armrest.Repo.hostname here.", env_var: nil, hidden: false, include_default: nil, name: "armrest.Elixir.Armrest.Repo.hostname", persist: true, see: "", to: "armrest.Elixir.Armrest.Repo.hostname", validators: []}, %Conform.Schema.Mapping{commented: false, datatype: :integer, default: 5432, doc: "Provide documentation for armrest.Elixir.Armrest.Repo.port here.", env_var: nil, hidden: false, include_default: nil, name: "armrest.Elixir.Armrest.Repo.port", persist: true, see: "", to: "armrest.Elixir.Armrest.Repo.port", validators: []}, %Conform.Schema.Mapping{commented: false, datatype: [list: :atom], default: [Armrest.Repo], doc: "Provide documentation for armrest.ecto_repos here.", env_var: nil, hidden: false, include_default: nil, name: "armrest.ecto_repos", persist: true, see: "", to: "armrest.ecto_repos", validators: []}, %Conform.Schema.Mapping{commented: false, datatype: :integer, default: 8080, doc: "Provide documentation for armrest.port here.", env_var: nil, hidden: false, include_default: nil, name: "armrest.port", persist: true, see: "", to: "armrest.port", validators: []}], transforms: [], validators: []}, [sasl: [errlog_type: :error], armrest: [{Armrest.Repo, [adapter: Ecto.Adapters.Postgres, database: "postgres", username: "postgres", password: "", hostname: "localhost", port: 5432]}, {:ecto_repos, [Armrest.Repo]}, {:port, 8080}]], #Reference<0.3150699304.4012507138.202283>)
    (conform) lib/conform.ex:102: Conform.process/1
    (elixir) lib/kernel/cli.ex:76: anonymous fn/3 in Kernel.CLI.exec_fun/2



START DONE!
```

When I run `/deps/conform/priv/bin/conform --conf config/armrest.conf --schema config/armrest.schema.exs` on my own computer, `sys.config` is successfully generated. But if I run the same script on the staging host, the error occurs. I haven't find out the reason.

**Comment by kenuyx** [comment]
It seems that the generated `sys.config` is wrong. The one on my staging host `/releases/0.1.0` is:

```
[{sasl,[{errlog_type,error}]},
 {armrest,[{'Elixir.Armrest.Repo',[{adapter,'Elixir.Ecto.Adapters.Postgres'},
                                   {database,<<"postgres">>},
                                   {username,<<"postgres">>},
                                   {password,<<>>},
                                   {hostname,<<"localhost">>},
                                   {port,5432}]},
           {ecto_repos,['Elixir.Armrest.Repo']},
           {port,8080}]}].
```

While the one generated by `mix conform.effective` is:

```
[{armrest,[{'Elixir.Armrest.Repo',[{adapter,'Elixir.Ecto.Adapters.Postgres'},
                                   {database,<<"postgres">>},
                                   {hostname,<<"localhost">>},
                                   {password,nil},
                                   {port,5432},
                                   {username,<<"postgres">>}]},
           {ecto_repos,['Elixir.Armrest.Repo']},
           {port,8080}]}].
```

**Comment by kenuyx** [comment]
I think I know the reason. The version of `Erlang/OTP` must not greater than 19.

**Comment by bitwalker** [comment]
I've fixed this in master, I'll be pushing a new release soon.

**Comment by lachezar** [comment]
I think you also need to re-compile the escript file for the changes in the `to_config` to become active - https://github.com/bitwalker/conform/blob/master/priv/bin/conform. 

Now I know what escript is :D

**Comment by bitwalker** [comment]
@lachezar Thanks! Done, and pushed to hex as 2.3.5
