### ISSUE TITLE
Conform crashed on some types of configuration

### ISSUE THREAD

**Issue by liveforeverx** [bitwalker/conform#26]
Seems, like `conform.new` can't accept all config types on generation.

```
proxy = [{:default_route, {{127, 0, 0, 1}, 1813, "secret"}},
         {:options, [{:type, :realm}, {:strip, true}, {:separator, '@'}]},
         {:routes, [{'test', {{127, 0, 0, 1}, 1815, "secret"}}]}]

config :eradius, :servers,
  proxy: {'127.0.0.1', [1812, 1813]}

config :eradius,
  session_nodes: [node],
  proxy: [{ {:eradius_proxy, 'proxy', proxy }, [{'127.0.0.1', "secret"}] }],
  logfile: './radius.log',
  client_ip: {0, 0, 0, 0}
```

```
** (Protocol.UndefinedError) protocol Enumerable not implemented for "secret"
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:112: Enumerable.reduce/3
    (elixir) lib/enum.ex:1398: Enum.reduce/3
    (elixir) lib/enum.ex:1106: Enum.map_reduce/3
    (elixir) lib/macro.ex:226: Macro.do_postwalk/3
    (elixir) lib/macro.ex:234: Macro.do_postwalk/3
    (elixir) lib/enum.ex:1102: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:226: Macro.do_postwalk/3


07:57:38.606 [error] Error in process <0.46.0> with exit value: {#{'__exception__'=>true,'__struct__'=>'Elixir.Protocol.UndefinedError',description=>nil,protocol=>'Elixir.Enumerable',value=><<6 bytes>>},[{'Elixir.Enumerable','impl_for!',1,[{file,"lib/enum.ex"},{line,1}]},{'Elixir.Enumerable',reduce,3,[{file...
```

**Comment by bitwalker** [comment]
I'll try and work on this in the morning, sorry for the mad delay.

**Comment by dersturm** [comment]
Had the same problem. Solved by removing configuration that uses a 3-tuple. Seems to be happen because the macro that creates the schema tries to convert those tuples into Enumerables (didn't read the source to confirm)

The part where my config had a problem:
```elixir
config :myapp, :consumer,
  queue_options: [
    durable: true,
    arguments: [
      {"x-dead-letter-exchange", :longstr, ""},
      {"x-dead-letter-routing-key", :longstr, "helix.error"}]]
```
Error returned:
```
$ mix conform.new
** (Protocol.UndefinedError) protocol Enumerable not implemented for ""
    (elixir) lib/enum.ex:1: Enumerable.impl_for!/1
    (elixir) lib/enum.ex:112: Enumerable.reduce/3
    (elixir) lib/enum.ex:1274: Enum.reduce/3
    (elixir) lib/enum.ex:1040: Enum.map_reduce/3
    (elixir) lib/macro.ex:226: Macro.do_postwalk/3
    (elixir) lib/enum.ex:1036: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:239: Macro.do_postwalk/3
    (elixir) lib/macro.ex:234: Macro.do_postwalk/3
```

Resolved by removing the `arguments` index
