### ISSUE TITLE
Failing test

### ISSUE THREAD

**Issue by tehprofessor** [bitwalker/conform#60]
I'm trying to run the test suite, from master, and I get this as a failing test:

```
 mix test
...............

  1) test can generate config as Elixir terms from .conf and schema with imports (ConfTranslateTest)
     test/conf_translate_test.exs:57
     ** (MatchError) no match of right hand side value: {:ok, []}
     stacktrace:
       test/conf_translate_test.exs:83: anonymous fn/5 in ConfTranslateTest.test can generate config as Elixir terms from .conf and schema with imports/1
       (ex_unit) lib/ex_unit/capture_io.ex:146: ExUnit.CaptureIO.do_capture_io/2
       (ex_unit) lib/ex_unit/capture_io.ex:119: ExUnit.CaptureIO.do_capture_io/3
       test/conf_translate_test.exs:66

............

Finished in 8.3 seconds (0.1s on load, 8.2s on tests)
28 tests, 1 failure

Randomized with seed 187604
```

I've looked at the code for that test and the `sys.config` file remains empty-- not sure what's exactly going on...

**Comment by bitwalker** [comment]
Fixed in master
