### ISSUE TITLE
Error running `mix conform.new` with pathological `config.exs`.

### ISSUE THREAD

**Issue by jamesotron** [bitwalker/conform#85]
Hi there.

I have the following chunk of awesomeness in my `config.exs`

``` elixir
config :rocket, Rocket.Endpoint,
  url: [host: "localhost"],
  root: Path.dirname(__DIR__),
  secret_key_base: "Hoopdie doopdie doo",
  debug_errors: false,
  http: [
    dispatch: [
      {:_, [
          {"/ws",               Pixie.Adapter.Cowboy.HttpHandler, {Pixie.Adapter.Plug, []}},
          {"/messagerocket.js", :cowboy_static,                   {:file, Path.join(Path.dirname(__DIR__),"priv/static/messagerocket.js")}},
          {:_,                  Plug.Adapters.Cowboy.Handler,     {Rocket.Endpoint, []}}
        ]
      }
    ]
  ]
```

And when I run `mix conform.new` I get the following amazing backtrace:

```
** (FunctionClauseError) no function clause matching in Macro.do_traverse_args/4
    (elixir) lib/macro.ex:290: Macro.do_traverse_args({Pixie.Adapter.Plug, []}, [], #Function<16.54478476/2 in Macro.postwalk/3>, #Function<11.54688206/2 in Conform.Utils.Code.stringify/1>)
    (elixir) lib/macro.ex:269: Macro.do_traverse/4
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:282: Macro.do_traverse/4
    (elixir) lib/macro.ex:277: Macro.do_traverse/4
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/enum.ex:1247: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (elixir) lib/macro.ex:282: Macro.do_traverse/4
```

I am so excited to raise this bug for you to fix. You must be very happy as the maintainer of a popular open source project to serve my every whim.

All kidding aside, this is with conform 2.1.1 on Elixir 1.3.2 with Erlang 19.  If there's any way I can help you diagnose this then feel free to ask.

**Comment by bitwalker** [comment]
Hi there! I've pushed a fix to master for this, sorry for the massive delay :(
